django/djangoshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('_admin/', admin.site.urls),
    path('', include('goodsapp.urls', namespace='main'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/goodsapp/urls.py
from django.urls import path
from .views import GoodsListView, GoodsCategoryListView

app_name = 'goodsapp'

urlpatterns = [
    path('', GoodsListView.as_view(), name='main'),
    path('category/<int:pk>', GoodsCategoryListView.as_view(), name='category'),
]

django/goodsapp/models.py
from django.db import models
from django.utils.timezone import now


class Goods(models.Model):
    PIECE = 'PI'
    PACKAGE = 'PA'
    UNITS = (
        (PIECE, 'шт.'),
        (PACKAGE, 'уп.')
    )

    name = models.CharField(verbose_name='Название', max_length=64)
    create_date = models.DateTimeField(auto_now_add=now)
    price = models.DecimalField(verbose_name='Цена', max_digits=8, decimal_places=2, default=0)
    unit = models.CharField(verbose_name='Ед. измерения', choices=UNITS, max_length=2)
    supplier = models.CharField(verbose_name='Поставщик', max_length=64)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'

django/goodsapp/models/category.py
from django.contrib.sites.models import Site
from django.contrib.sites.managers import CurrentSiteManager
from django.db import models
from django.utils.timezone import now


class Category(models.Model):
    name = models.CharField('Название', max_length=64)
    create_date = models.DateTimeField(auto_now_add=now)
    site = models.ForeignKey(Site, on_delete=models.CASCADE, null=True)
    objects = models.Manager()
    on_site = CurrentSiteManager('site')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ['-create_date']

django/goodsapp/models/goods.py
from django.contrib.sites.managers import CurrentSiteManager
from django.contrib.sites.models import Site
from django.db import models
from django.utils.timezone import now

from goodsapp.models.category import Category


class Goods(models.Model):
    PIECE = 'PI'
    PACKAGE = 'PA'
    UNITS = (
        (PIECE, 'шт.'),
        (PACKAGE, 'уп.')
    )

    name = models.CharField(verbose_name='Название', max_length=64)
    create_date = models.DateTimeField(auto_now_add=now)
    price = models.DecimalField(verbose_name='Цена', max_digits=8, decimal_places=2, default=0)
    unit = models.CharField(verbose_name='Ед. измерения', choices=UNITS, max_length=2)
    supplier = models.CharField(verbose_name='Поставщик', max_length=64)
    category = models.ManyToManyField(Category)
    site = models.ManyToManyField(Site)
    image = models.ImageField('Изображение', upload_to='image_goods/', null=True)

    objects = models.Manager()
    on_site = CurrentSiteManager('site')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'
        ordering = ['-create_date']

django/hitcountapp/models.py
from django.db import models


class HitCount(models.Model):
    path = models.CharField(max_length=512)
    hits = models.IntegerField(default=1)
    user = models.CharField(max_length=128)

    def __str__(self):
        user = self.user if self.user else 'AnonymousUser'
        return f'{user} : [ {self.path} ]   ({self.hits})'

django/goodsapp/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import ListView

from .models import Goods


class GoodsListView(ListView):
    model = Goods
    # queryset = Goods.objects.prefetch_related('category').all()
    queryset = Goods.on_site.prefetch_related('category').all()
    template_name = 'goods_list.html'


class GoodsCategoryListView(ListView):
    model = Goods
    template_name = 'category_list.html'

    def get_queryset(self):
        # queryset = Goods.objects.prefetch_related('category').filter(category=self.kwargs['pk'])
        queryset = Goods.on_site.prefetch_related('category').filter(category=self.kwargs['pk'])
        return queryset

django/hitcountapp/views.py
from django.shortcuts import render

# Create your views here.

django/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% block header %}
        {% include 'includes/inc_header.html' %}
    {% endblock header %}

<div class="main">

    {% block content %}

    {% endblock content %}

</div>
</body>
</html>

django/templates/category_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <table class="table" style="margin-top:30px">
        <thead>
            <tr>
                <th scope="col">Название</th>
                <th scope="col">Цена</th>
                <th scope="col">Поставщик</th>
                <th scope="col">Категория</th>
            </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
            <tr>
                <td>{{ object.name }}</td>
                <td>{{ object.price }} руб./{{ object.get_unit_display }}</td>
                <td>{{ object.supplier }}</td>
                <td>
                    {% for category in object.category.all %}
                    {{category}}
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

django/templates/goods_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <table class="table" style="margin-top:30px">
        <thead>
            <tr>
                <th scope="col">Название</th>
                <th scope="col">Цена</th>
                <th scope="col">Поставщик</th>
                <th scope="col">Категория</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
            <tr>
                <td>{{ object.name }}</td>
                <td>{{ object.price }} руб./{{ object.get_unit_display }}</td>
                <td>{{ object.supplier }}</td>
                <td>
                    {% for category in object.category.all %}
                    {{category}}
                    {% endfor %}
                </td>
                <td>
                    {% if object.image %}
                    <img src="{{ object.image.url}}" alt="pic" width="100">
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

django/templates/includes/inc_header.html
<nav class="navbar navbar-light navbar-expand-lg" style="background-color: #e3f2fd;">
  <div class="container">
    <a class="navbar-brand" href="{% url 'main:main' %}">DjangoShop</a>{{site.name}}
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'main:main' %}">Home</a>
        </li>
        {% for category in category_list %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:category' category.pk %}">{{ category.name }}</a>
        </li>
        {% endfor %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'admin:index' %}">Админка</a>
        </li>
<!--        <li class="nav-item">-->
<!--          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>-->
<!--        </li>-->
      </ul>
    </div>
  </div>
</nav>